Javad Delta 3 (TTY1):
  baud: !!python/unicode '9600'
  port: /dev/ttyUSB0
Memsic VG440:
  baud: !!python/unicode '57600'
  port: /dev/ttyUSB0
MicroStrain 3DM-GX5-15:
  baud: !!python/unicode '115200'
  frequency: !!python/unicode '100'
  port: /dev/ttyACM0
PointGrey Grasshoper 3 (USB1):
  CalibrationFile: ''
Serial GNSS:
  baud: !!python/unicode '9600'
  port: /dev/ttyUSB0
Velodyne + Hokuyo 2D URG:
  device_address: /dev/ttyACM0
  device_type: false
  hokuyo_topic: /scan
  ip_address: 192.168.0.10
  max_range: 30.0
  output_topic: /vh/points_raw
  pitch: 0.0
  publish_intensity: true
  roll: 0.0
  serial_port: /dev/ttyACM0
  use_ethernet: false
  use_hokuyo: true
  use_hokuyo_driver: false
  use_velodyne: true
  use_velodyne_driver: false
  velodyne_calib_path: /home/alexandr/autoware-dev/autoware-dev-alex/ros/src/sensing/drivers/lidar/packages/velodyne_hokuyo/nodes/velodyne_pointcloud/params/VLP16db.yaml
  velodyne_topic: /velodyne_points
  velodyne_type: 3
  x: 0.1
  y: 0.0
  yaw: 0.0
  z: -1.0
Velodyne HDL-32e:
  calibration: /home/alexandr/autoware-dev/autoware-dev-alex/ros/src/sensing/drivers/lidar/packages/velodyne/velodyne_pointcloud/params/32db.yaml
Velodyne HDL-64e-S2:
  calibration: ''
Velodyne HDL-64e-S3:
  calibration: /home/alexandr/autoware-dev/autoware-dev-alex/ros/src/sensing/drivers/lidar/packages/velodyne/velodyne_pointcloud/params/64e_utexas.yaml
Velodyne VLP-16:
  calibration: /home/alexandr/autoware-dev/autoware-dev-alex/ros/src/sensing/drivers/lidar/packages/velodyne/velodyne_pointcloud/params/VLP16db.yaml
Xsens MTi-300:
  baud: !!python/unicode '115200'
  frequency: !!python/unicode '100'
  mode: !!python/unicode '3'
  port: /dev/ttyUSB1
  wait_sec: 3
astar_navi:
  use_back: false
  waypoint_velocity_kmph: 5.0
booted_cmds:
  names:
  - setup_tf
  - vehicle_model
  - point_cloud
  - tf
  - Velodyne VLP-16
  - Hokuyo TOP-URG
  - voxel_grid_filter
  - ground_filter
  - rviz_qs
  - way_planner
  - ndt_matching
  - vel_pose_connect
  - dp_planner
  - pure_pursuit
  - twist_filter
  - euclidean_cluster
calibration_publisher:
  camera_id: ''
  file: ''
  publish_camera_info: false
  publish_extrinsic_mat: true
  register_lidar2camera_tf: true
  solo_camera: true
can_listener:
  channel: 0
car_dpm:
  Lambda: 10
  group_threshold: 0.1
  num_bins: 9
  num_cells: 8
  score_threshold: -0.5
car_fusion:
  car: true
  dispersion: 1.0
  max_height: 2.0
  max_low_height: -1.0
  min_low_height: -1.5
  min_points: 2
  pedestrian: false
  sync: false
car_kf:
  camera_id: ''
  car: true
  default_lifespan: 8
  error_estimate_covariance: 1000000.0
  initial_lifespan: 4
  measurement_noise_covariance: 25.0
  noise_covariance: 1.0
  orb_features: 2000
  pedestrian: false
  percentage_of_overlapping: 0.0
  sync: false
  use_orb: 0
detection_qs:
  file: ''
dist_transform:
  map_topic: /realtime_cost_map
  max_distance: 3.0
distance_filter:
  measurement_range: 200
  sample_num: 10000
  sync: false
dp_planner:
  enabTrajectoryVelocities: true
  enableFollowing: true
  enableLaneChange: false
  enableObjectTracking: true
  enableOutsideControl: false
  enablePlannerDynamicSwitch: false
  enableStopSignBehavior: false
  enableSwerving: true
  enableTrafficLightBehavior: false
  horizontalSafetyDistance: 0.2
  mapFileName: /home/alexandr/TsukubaChallenge/2017/2017-10-15/map/tsukuba_second-map.kml
  mapSource: 2
  maxDistanceToAvoid: 0.5
  maxLocalPlanDistance: 10.0
  maxVelocity: 0.5
  minDistanceToAvoid: 2.0
  minFollowingDistance: 5.0
  pathDensity: 0.25
  rollOutDensity: 0.3
  rollOutsNumber: 6
  samplingOutMargin: 2.0
  samplingTipMargin: 1.0
  velocitySource: 1
  verticalSafetyDistance: 0.5
euclidean_cluster:
  clip_max_height: 0.5
  clip_min_height: -0.8
  cluster_merge_threshold: 1.5
  cluster_size_max: 100000
  cluster_size_min: 5
  clustering_distances: '[15,30,45,60]'
  clustering_thresholds: '[0.5,1.1,1.6,2.1,2.6]'
  downsample_cloud: false
  keep_lane_left_distance: 0.2
  keep_lane_right_distance: 0.2
  keep_lanes: false
  leaf_size: 0.25
  output_frame: map
  points_node: /points_raw
  pose_estimation: true
  publish_filtered: false
  remove_ground: true
  remove_points_upto: 0.1
  sync: false
  use_diffnormals: false
  use_gpu: true
  use_vector_map: false
  vectormap_frame: map
feat_proj:
  camera_id: ''
  x: 0
  y: 0
ff_waypoint_follower:
  maxVelocity: 1.0
  minPursuiteDistance: 2.5
  signal: 0
  steerGainKD: 0.01
  steerGainKI: 0.02
  steerGainKP: 0.07
  steeringDelay: 0.85
ground_filter:
  budget: 20
  cpu_chks:
  - true
  - true
  - true
  - true
  - true
  - true
  - true
  - true
  nice: 0
  period: 100
  policy: !!python/unicode 'FIFO'
  prio: 99
  real_time: false
image_viewer:
  camera_id: ''
lane_navi:
  output_file: /tmp/lane_waypoint.csv
  velocity: 40.0
lane_rule:
  acceleration: 1.0
  number_of_zeros_ahead: 0
  number_of_zeros_behind: 0
  stopline_search_radius: 1.0
lane_select:
  distance_threshold_neighbor_lanes: 5.0
  enablePlannerDynamicSwitch: false
  lane_change_interval: 10.0
  lane_change_target_minimum: 10.0
  lane_change_target_ratio: 5.0
  vector_length_hermite_curve: 10.0
laserscan2costmap:
  map_size_x: 500
  map_size_y: 500
  resolution: 0.1
  scan_size_x: 1000
  scan_size_y: 1000
  scan_topic: /scan
  sensor_frame: /velodyne
localization_qs:
  file: ''
map_qs:
  file: ''
mission_planning_qs:
  file: ''
motion_planning_qs:
  file: ''
ndt_matching:
  error_threshold: 3.0
  get_height: false
  init_pos_gnss: 0
  max_iterations: 30
  pitch: 0.0
  resolution: 1.0
  roll: 0.0
  step_size: 0.1
  sync: false
  trans_epsilon: 0.01
  use_openmp: false
  use_predict_pose: 1
  x: 0.0
  y: 0.0
  yaw: 0.0
  z: 0.0
ndt_monitor:
  history_size: 10
  max_speed: 1.5
  speed_down_factor: 0.5
  threshold_stop: 5.0
  threshold_warn: 3.0
obstacle_avoid:
  avoid_distance: 3.0
  avoid_velocity_limit_mps: 1.0
  avoidance: false
  budget: 20
  cpu_chks:
  - true
  - true
  - true
  - true
  - true
  - true
  - true
  - true
  nice: 0
  period: 100
  policy: !!python/unicode 'FIFO'
  prio: 99
  real_time: false
pcd_binarizer:
  path_pcd_binarizer: ''
  point_type: !!python/unicode 'PointXYZ'
pcd_filter:
  leaf_size: 0.2
  path_pcd_filter: ''
  point_type: !!python/unicode 'PointXYZ'
pedestrian_dpm:
  Lambda: 10
  group_threshold: 0.3
  num_bins: 9
  num_cells: 8
  score_threshold: 0.6
pedestrian_fusion:
  dispersion: 1.0
  max_height: 2.0
  max_low_height: -1.0
  min_low_height: -1.5
  min_points: 2
pedestrian_kf:
  default_lifespan: 8
  error_estimate_covariance: 1000000.0
  initial_lifespan: 4
  measurement_noise_covariance: 25.0
  noise_covariance: 1.0
  orb_features: 2000
  percentage_of_overlapping: 0.0
  use_orb: 0
play_rosbag_play:
  file: /media/alexandr/AlexLogs/tc_2017-11-04-15-39-08.bag
  rate: ''
  repeat: false
  start: ''
point_cloud:
  path_area_list: None
  path_area_list_cmd_param: null
  path_pcd: /home/alexandr/TsukubaChallenge/2017/2017-10-15/map/bin_tc-2017-10-15--ndmap.pcd
  scene_num: noupdate
points2costmap:
  cell_height: 150
  cell_width: 300
  offset_x: 25.0
  offset_y: 0.0
  offset_z: -2.0
  points_topic: /points_lanes
  resolution: 0.2
points_image:
  camera_id: ''
  sync: false
points_image_viewer:
  camera_id: ''
pure_pursuit:
  displacement_threshold: 0.0
  is_linear_interpolation: true
  lookahead_distance: 2.0
  lookahead_ratio: 1.0
  minimum_lookahead_distance: 1.0
  param_flag: 0
  publishes_for_steering_robot: false
  relative_angle_threshold: 0
  velocity: 1.5
random_filter:
  measurement_range: 200
  sample_num: 10000
  sync: false
region_tlr:
  camera_id: ''
  data: false
region_tlr_ssd:
  budget: 20
  cpu_chks:
  - true
  - true
  - true
  - true
  - true
  - true
  - true
  - true
  nice: 0
  period: 100
  policy: !!python/unicode 'FIFO'
  prio: 99
  real_time: false
ring_filter:
  measurement_range: 200
  ring_div: 3
  sync: false
  voxel_leaf_size: 2.0
sensing_qs:
  file: ''
setup_tf:
  frame_id: /base_link
  localizer_cmd_param: /velodyne
  localizer_rosparam: velodyne
  period_in_ms: 10
  pitch: 0.0
  roll: 0.0
  x: 0.3
  y: 0.0
  yaw: 0.0
  z: 1.2
ssd_unc:
  camera_id: ''
  gpu_device_id: 0
  image_raw_topic_str: /image_raw
  network_definition_file: /home/alexandr/ssdcaffe/models/VGGNet/VOC0712Plus/SSD_300x300/deploy.prototxt
  pretrained_model_file: /home/alexandr/ssdcaffe/models/VGGNet/VOC0712Plus/SSD_300x300/VGG_VOC0712Plus_SSD_300x300_iter_240000.caffemodel
  score_threshold: 0.6
  use_gpu: false
tf:
  file: /home/alexandr/autoware-dev/autoware-dev-alex/ros/src/.config/tf/tf_local.launch
twist_filter:
  lateral_accel_limit: 0.8
  lowpass_gain_angular_z: 0.0
  lowpass_gain_linear_x: 0.0
vector_map:
  path_vec: /home/alexandr/seiya/meidai/nu_garden_map.kml
vehicle_info:
  info_path: ''
vehicle_model:
  model_path: ''
vel_pose_connect:
  sim_mode: false
  topic_pose_stamped: /ndt_pose
  topic_twist_stamped: /estimate_twist
velocity_set:
  deceleration: 0.7
  deceleration_range: 1
  detection_height_bottom: -1.5
  detection_height_top: 1.0
  detection_range: 1.3
  enablePlannerDynamicSwitch: false
  enable_multiple_crosswalk_detection: false
  others_distance: 3.0
  points_topic: points_no_ground
  temporal_waypoints_size: 100.0
  threshold_points: 5
  use_crosswalk_detection: false
  velocity_change_limit: 7.0
virtual_scan_image:
  camera_id: ''
  sync: false
voxel_grid_filter:
  measurement_range: 100
  sync: false
  voxel_leaf_size: 2.0
vscan_image_d_viewer:
  camera_id: ''
vscan_image_viewer:
  camera_id: ''
way_planner:
  enableHMI: false
  enableLaneChange: false
  enableReplan: false
  enableSmoothing: false
  mapFileName: /home/alexandr/TsukubaChallenge/2017/2017-10-15/map/tsukuba_second-map.kml
  mapSource: 2
  pathDensity: 0.75
  velocitySource: 1
waypoint_loader:
  decelerate: 1.0
  multi_lane_csv: /media/alexandr/AlexLogs/Log-data/TsukubaChallenge/2017/2017-10-15/map/saved_waypoints-1600s.csv
wf_simulator:
  accel_rate: 0.3
  angle_error: 0.0
  initialize_source: !!python/unicode 'Rviz'
  position_error: 0.0
